# Generated by Django 4.1.1 on 2022-12-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0002_alter_wishlist_experience_alter_wishlist_room_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="room",
            new_name="rooms",
        ),
    ]
